feat: receive rabbit messages and ingest from harvesters
Informasjonsforvaltning/fdk-fulltext-search-rabbit-consumer pull request #1
Opened 2020-08-14 13:47 UTC by Chlenix

2020-08-17 03:43 UTC, NilsOveTen requested changes
Nå vet jeg ikke hva du ble enig med @stigbd om, men jeg er noe negativt innstilt til at denne skal ha direkte kontakt med elastic.

Jeg var av inntrykket at denne kun skulle håndtere rabbit, og starte reindeksering osv vha endepunkter i fulltext, ingenting annet.

Om det er korrekt at ingest-koden skal flyttes hit så savner jeg tester...

2020-08-17 03:43 UTC, NilsOveTen commented on ingest/ingest.py
> +    status = "erros occured"
erros

2020-08-17 03:43 UTC, NilsOveTen commented on elasticsearch/create_concepts_index.json
> +{
Skal denne ha direkte kontakt med elastic?

2020-08-17 03:43 UTC, NilsOveTen commented on ingest/ingest.py
> +def reindex():
Så vi flytter alt ingest-relatert inn i her?

2020-08-17 06:59 UTC, stigbd commented
Det må lagast ein README.md som forklarer kva denne tjenesten skal gjere.

2020-08-24 10:03 UTC, NilsOveTen approved these changes

2020-08-24 10:03 UTC, NilsOveTen commented on test/test_build.py
> +    assert True
Grundig test :+1:

2020-08-24 11:55 UTC, merged